[package]
name = "limit_flop"
version = "0.1.0"
edition = "2024"

[dependencies]
file = "0.1.1"
io = "0.0.2"
oncelock = "0.1.0-alpha.0"
pyo3 = "0.27.2"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }

[build-dependencies]

cc = "1.0"

